### ISSUE TITLE
Python version mismatch between Pipfile and platform.app.yaml

### ISSUE THREAD

**Issue by gilzow** [platformsh-templates/wagtail#22]
[Pipfile has a requirement of python 3.7](https://github.com/platformsh-templates/wagtail/blob/master/Pipfile#L14), but the contain is set to [python 3.8 in platform.app.yaml](https://github.com/platformsh-templates/wagtail/blob/master/.platform.app.yaml#L10). These should be aligned; suggest updating requirement in Pipfile to 3.8.

While we're making changes, we should update [pipenv from 2018.10.13](https://github.com/platformsh-templates/wagtail/blob/master/.platform.app.yaml#L15) to the latest version.

**Comment by chadwcarlson** [comment]
All bumped to 3.9 in https://github.com/platformsh-templates/wagtail/pull/27
